import { type DbClient, downloads, isos } from "@iso/db";
import { eq } from "drizzle-orm";

export class DownloadService {
  private readonly db: DbClient;

  constructor(db: DbClient) {
    this.db = db;
  }

  async getDirectUrl(isoId: number, userId?: string) {
    const [iso] = await this.db
      .select({ driveId: isos.driveId, filename: isos.filename })
      .from(isos)
      .where(eq(isos.id, isoId))
      .limit(1);

    if (!iso) {
      return null;
    }

    await this.db.insert(downloads).values({
      isoId,
      userId,
      downloadType: "direct",
    });

    const url = `https://drive.google.com/uc?id=${iso.driveId}&export=download`;
    const expiresAt = new Date(Date.now() + 3_600_000).toISOString();

    return { url, expiresAt, filename: iso.filename };
  }

  async getMagnetUri(isoId: number) {
    const [iso] = await this.db
      .select({
        filename: isos.filename,
        checksumSha256: isos.checksumSha256,
        size: isos.size,
      })
      .from(isos)
      .where(eq(isos.id, isoId))
      .limit(1);

    if (!iso?.checksumSha256) {
      return null;
    }

    const magnet = `magnet:?xt=urn:btih:${iso.checksumSha256}&dn=${encodeURIComponent(iso.filename)}`;
    return { magnet };
  }

  async getTorrent(isoId: number) {
    const [iso] = await this.db
      .select({
        filename: isos.filename,
        driveId: isos.driveId,
        checksumSha256: isos.checksumSha256,
        size: isos.size,
      })
      .from(isos)
      .where(eq(isos.id, isoId))
      .limit(1);

    if (!iso?.checksumSha256) {
      return null;
    }

    // Generate a simple torrent file (bencode format)
    const webSeedUrl = `https://drive.google.com/uc?id=${iso.driveId}&export=download`;
    const torrent = this.encodeTorrent({
      announce: "udp://tracker.opentrackr.org:1337/announce",
      "announce-list": [
        ["udp://tracker.opentrackr.org:1337/announce"],
        ["udp://open.stealth.si:80/announce"],
        ["udp://tracker.torrent.eu.org:451/announce"],
      ],
      info: {
        name: iso.filename,
        "piece length": 262_144, // 256KB pieces
        length: iso.size || 0,
        pieces: iso.checksumSha256, // Simplified - real impl needs actual piece hashes
      },
      "url-list": [webSeedUrl],
      "creation date": Math.floor(Date.now() / 1000),
      comment: "Generated by ISO Archive",
    });

    return { data: torrent, filename: iso.filename };
  }

  private encodeTorrent(obj: unknown): string {
    return this.bencode(obj);
  }

  private bencode(data: unknown): string {
    if (typeof data === "string") {
      return `${data.length}:${data}`;
    }
    if (typeof data === "number") {
      return `i${data}e`;
    }
    if (Array.isArray(data)) {
      return `l${data.map((item) => this.bencode(item)).join("")}e`;
    }
    if (typeof data === "object" && data !== null) {
      const entries = Object.entries(data as Record<string, unknown>).sort(
        ([a], [b]) => a.localeCompare(b)
      );
      const encoded = entries
        .map(([key, value]) => `${this.bencode(key)}${this.bencode(value)}`)
        .join("");
      return `d${encoded}e`;
    }
    return "";
  }
}
